// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(value, structured) {
  return {
    content: [{ type: "text", text: typeof value === "string" ? value : JSON.stringify(value, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : errorResult("Not authenticated.");
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Blank2Branded shop catalogue by title, handle or brand. Returns product title, handle, status, collection and base price.",
  inputSchema: {
    query: z.string().trim().describe("Text to match against product title, handle or brand.").optional(),
    collection: z.enum(["apparel", "corporate"]).describe("Limit to one collection.").optional(),
    status: z.enum(["active", "draft"]).describe("Filter by publish status.").optional(),
    limit: z.number().int().describe("Max results (default 20, max 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, collection, status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("shop_products").select("id,title,handle,brand,collection,status,base_price,currency_code").limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (query) q = q.or(`title.ilike.%${query}%,handle.ilike.%${query}%,brand.ilike.%${query}%`);
    if (collection) q = q.eq("collection", collection);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { products: data ?? [] });
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Get one shop product by handle, including its variants (colour/size, price, stock) and branding options (method, position, size, per-unit and setup pricing).",
  inputSchema: {
    handle: z2.string().trim().describe("The product handle, e.g. 'unisex-dry-fit-t-shirt'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ handle }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const { data: product, error } = await supabase.from("shop_products").select(
      "id,title,handle,brand,description,product_features,collection,status,base_price,currency_code,meta_title,meta_description"
    ).eq("handle", handle).maybeSingle();
    if (error) return errorResult(error.message);
    if (!product) return errorResult(`No product found with handle '${handle}'.`);
    const [{ data: variants }, { data: branding }] = await Promise.all([
      supabase.from("shop_product_variants").select("id,sku,option1_name,option1_value,option2_name,option2_value,price,stock,available").eq("product_id", product.id).order("position"),
      supabase.from("shop_product_branding_options").select("*").eq("product_id", product.id)
    ]);
    const result = { product, variants: variants ?? [], branding_options: branding ?? [] };
    return textResult(result, result);
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "List orders",
  description: "List recent Blank2Branded orders visible to the signed-in user, with customer, totals, status and line items.",
  inputSchema: {
    status: z3.string().trim().describe("Filter by order status, e.g. 'pending' or 'paid'.").optional(),
    limit: z3.number().int().describe("Max orders to return (default 10, max 50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("orders").select(
      "id,order_number,created_at,status,customer_name,customer_email,customer_phone,subtotal,shipping_amount,total_amount,ship_city,ship_province,order_items(product_name,variant_label,quantity,unit_price,line_total)"
    ).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { orders: data ?? [] });
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List Blank2Branded blog posts with title, slug, status, publish date and SEO metadata. Use to review content or find a post to update.",
  inputSchema: {
    status: z4.enum(["published", "scheduled", "draft"]).describe("Filter by post status.").optional(),
    query: z4.string().trim().describe("Match against post title or slug.").optional(),
    limit: z4.number().int().describe("Max posts to return (default 20, max 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, query, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("posts").select("id,title,slug,status,published_at,updated_at,excerpt,meta_title,meta_description,keywords").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) q = q.eq("status", status);
    if (query) q = q.or(`title.ilike.%${query}%,slug.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data ?? [], { posts: data ?? [] });
  }
});

// src/lib/mcp/tools/create-blog-draft.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
}
var create_blog_draft_default = defineTool5({
  name: "create_blog_draft",
  title: "Create blog draft",
  description: "Create a new blog post in draft status (never published directly). Provide the title and HTML content, plus optional SEO fields.",
  inputSchema: {
    title: z5.string().trim().describe("Post title."),
    content: z5.string().describe("Post body as HTML."),
    excerpt: z5.string().trim().describe("Short summary shown in listings.").optional(),
    slug: z5.string().trim().describe("URL slug. Derived from the title when omitted.").optional(),
    meta_title: z5.string().trim().describe("SEO title tag.").optional(),
    meta_description: z5.string().trim().describe("SEO meta description.").optional(),
    keywords: z5.string().trim().describe("Comma-separated focus keywords.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const slug = slugify(input.slug || input.title);
    if (!slug) return errorResult("Could not derive a valid slug from the title.");
    const { data, error } = await supabaseForUser(ctx).from("posts").insert({
      title: input.title,
      slug,
      content: input.content,
      excerpt: input.excerpt ?? null,
      meta_title: input.meta_title ?? null,
      meta_description: input.meta_description ?? null,
      keywords: input.keywords ?? null,
      status: "draft",
      created_by: ctx.getUserId()
    }).select("id,title,slug,status").single();
    if (error) return errorResult(error.message);
    return textResult(`Draft created: ${data.title} (/blog/${data.slug})`, { post: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "enpdahmqwhdukbnykqyy";
var mcp_default = defineMcp({
  name: "blank2branded-mcp",
  title: "Blank2Branded",
  version: "0.1.0",
  instructions: "Tools for the Blank2Branded store (DTF printing and blank apparel, South Africa). Use `search_products` and `get_product` for catalogue, pricing, variants and branding options; `list_orders` for recent customer orders; `list_blog_posts` and `create_blog_draft` for blog content. New posts are always created as drafts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_orders_default, list_blog_posts_default, create_blog_draft_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
